---
title: "PS270 Final Project"
author: "Syver Gulbrandsen"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts


A few areas which I am interested in exploring involve local elections, maybe something on the advertising aspect in elections or on economic downturns and how those effect elections.
```{r}
library(tidyverse)
data<-read_csv("data/govrev_v3.csv")
head(data)
```

I switched my original interest from economic downturns and how those effect elections to a countries development and their taxes. I could not find a data set that matched what I wanted to accomplish for my first interest and then I came across this data set and found it pretty interesting.
##Theory
My data set that I am using is from Per F. Anderson and is titled "Financing the State: Government Tax Revenue from 1800 to 2024".It has information on the size and composition of government tax revenue from 31 countries between 1800 and 2024. My research question that I hope to answer using this data is Do wealthier countries rely more on direct taxes rather than indirect taxes compared to poorer countries? My hypothesis is that as countries get wealthier (as real gdp increases), they rely more on direct taxes vs indirect since the more developed they are, the better their institutions in place are and the better able they are to monitor and collect taxes on things like income efficiently. Poorer countries, may rely on indirect taxes more which are easier to collect. The explanatory variable would be gdp measuring total economic output. My outcome variable will be centaxdirectsh, which is direct tax revenue's share out of total tax revenue. I would also like to see how another variable centaxindirectsh which is the indirect tax revenue's share out of total tax revenue. The pattern that would prove my thesis, is that as a country develops over time, the centaxdirectsh increases along with GDP, so as countries get more developed they rely more on direct taxes, vs as countries who are less developed rely on centaxindirectsh. 

